version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_HTTP_PORT: 8123
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123

volumes:
  clickhouse_data: